### ISSUE TITLE
No "exports" main defined in package.json

### ISSUE THREAD

**Issue by JustDoItSascha** [altcha-org/altcha-lib#1]
Hey! I'm trying to use altcha-lib in a NestJS backend and when I import it, I get this error:

`Error: No "exports" main defined in node_modules/altcha-lib/package-json`.

Could you please add the exports field to the package.json? Thank you!

**Comment by ovx** [comment]
Hi, thanks for reporting. The problem was caused by the missing commonjs build, which is now added in the version 0.1.2.
