### ISSUE TITLE
Integration with Firebase Appcheck

### ISSUE THREAD

**Issue by andrevferreiraa** [altcha-org/altcha-lib#10]
Hey everyone. I'm trying to implement **altcha** with Firebase Appcheck on a Nuxt3 application using Firebase Functions as the BE. The functions themselves work well standalone, but they stop responding once they are integrated with the CustomProvider getToken function:

/// plugins/appcheck.ts on Client side

```
import { initializeAppCheck, CustomProvider } from 'firebase/app-check'
import { getFunctions, httpsCallable } from 'firebase/functions'
import { solveChallenge } from 'altcha-lib'

export default defineNuxtPlugin(async (nuxtApp) => {
  if (!process.client) return

  const firebaseApp = nuxtApp.vueApp.$nuxt.$firebaseApp
  const functions = getFunctions(firebaseApp)
  const fetchAppCheckToken = httpsCallable(functions, 'fetchAppCheckToken')
  const createAppCheckChallenge = httpsCallable(functions, 'createAppCheckChallenge')
  const appCheckProvider = new CustomProvider({
    getToken: async () => {
      const challengeResponse = await createAppCheckChallenge()

      // Solve the challenge
      const { promise } = solveChallenge(challengeResponse.data.challenge, challengeResponse.data.salt)
      const solution = await promise

      // Submit the solution
      const token = await fetchAppCheckToken({
        solution,
      })
      return token
    },
  })
  initializeAppCheck(firebaseApp, {
    provider: appCheckProvider,
  })
})
```

// FIrebase functions

```
const hmacKey = '...';

exports.createAppCheckChallenge = functions.https.onCall(async () => {
    functions.logger.log('Creating Altcha challenge');
    try {
        const challengeResponse = await createChallenge({
            hmacKey,
            ttlMillis: 60000,
        });
        functions.logger.log(challengeResponse);
        return challengeResponse;
    } catch (error) {
        functions.logger.error(error);
        throw new functions.https.HttpsError(
            error.errorInfo.code,
            error.errorInfo.message
        );
    }
});

exports.fetchAppCheckToken = functions.https.onCall(async (data) => {
    functions.logger.log('Verifying Altcha challenge');
    functions.logger.log(data.solution)
    try {
        // Verify the Altcha challenge response
        const isValid = await verifySolution(data.solution, hmacKey);

        functions.logger.log('Altcha verification result:', isValid);

        if (isValid) {
            // Create an App Check token
            const token = await createAppCheckToken(data.solution);
            return { token };
        } else {
            functions.logger.error('Altcha verification failed');
            throw new functions.https.HttpsError(
                'permission-denied',
                'Altcha verification failed'
            );
        }
    } catch (error) {
        functions.logger.error(error);
        throw new functions.https.HttpsError(
            'permission-denied',
            'Altcha verification failed'
        );
    }
});

async function createAppCheckToken(altchaData) {
    functions.logger.log('Altcha verification successful');
    try {
        const appCheck = admin.appCheck();
        const ttlMillis = 3600 * 1000;
        const appId = admin.instanceId().app.options.appId;
        const token = await appCheck.createToken(appId, {
            ttlMillis,
            customClaims: {
                altcha_verified: true,
                altcha_response_id: altchaData.response_id,
                origin: altchaData.origin,
            },
        });
        functions.logger.log(
            'App Check token created successfully:',
            token.token
        )
        return token.token;
    } catch (error) {
        functions.logger.error('Altcha verification failed');
        throw new functions.https.HttpsError(
            'App Check token created failed',
            'Altcha verification failed'
        );
    }
}
```

Am i doing something wrong here? I believe an example of how to correctly implement this would help out a lot of people. 

Appreciate your help

**Comment by ovx** [comment]
Hi, what do you mean by "stop responding"? Do you get some error? 

At the moment, there's no example on usage with Firebase, there's a related feature request (https://github.com/altcha-org/altcha/issues/69) I'm still investigating and planning to create an official firebase extensions with examples.

**Comment by andrevferreiraa** [comment]
Hey @ovx!

There is no errors, simply a timeout. I know that `createAppCheckChallenge` is being called but it never returns anything or even throws an error. It simply stops working.

An official firebase extension would be greatly welcomed!

**Comment by ovx** [comment]
The function `createAppCheckChallenge` is just a wrapper around the HTTP request, so it should return or fail, maybe it's the function `getToken` that timeouts? Computing a solution takes some time, so if there is a timeout for `getToken` function, it could fail. I would try to mock low complexity challenges by setting `number: 1` to `createChallenge` forcing it to always use number `1` which requires only two iterations of computing. If it helps, you will have to increase the timeout on `getToken` or use lower complexity of the challenge.

**Comment by ovx** [comment]
Regarding the timeouts, it looks like `httpsCallable` doesn't really work - it doesn't call the API and gets stuck. Replace them with normal `fetch` and it should work (event Cloudflare's App Check integration uses fetch, they probably had the same problem).

Also  I created the [ALTCHA extension](https://console.firebase.google.com/project/_/extensions/install?ref=altcha/altcha-app-check-provider@0.0.4-alpha.0) (in alpha version), but no matter what, it fails with "Permission 'iam.serviceAccounts.signBlob' denied on resource". I added the role `serviceAccountTokenCreator` to the service account, but the issue remains ([stackoverflow](https://stackoverflow.com/questions/57564505/unable-to-assign-iam-serviceaccounts-signblob-permission)). Anybody encountered this issue? Any idea how to actually solve it?

**Comment by andrevferreiraa** [comment]
Hey @ovx , thanks for your investigation! I'll try fetch requests instead of calllables.

Regarding this "Permission 'iam.serviceAccounts.signBlob' denied on resource"., I've had it happen before where adding the role to the service account on the google console did not do the job, and i had to use the terminal a gcloud cli to do that. Then it worked!

**Comment by andrevferreiraa** [comment]
Thanks for your tips, i've managed to make some progress. Example of updated endpoint:

```
exports.fetchAppCheckToken = functions.https.onRequest(async (req, res) => {
    cors(req, res, async () => {
        try {
            const solution = req.body.solution;
            // Verify the Altcha challenge response
            const isValid = await verifySolution(solution, hmacKey);
            functions.logger.log('Altcha verification result:', isValid);
            if (isValid) {
                // Create an App Check token
                const token = await createAppCheckToken(solution);
                res.send(token)
            } else {
                functions.logger.error('Altcha verification failed');
                throw new functions.https.HttpsError(
                    'permission-denied',
                    'Altcha verification failed'
                );
            }
        } catch (error) {
            functions.logger.error(error);
            throw new functions.https.HttpsError(
                'permission-denied',
                error
            );
        }
    });
});
```

Changed to onRequest and added cors and it's smooth sailing! 
My only issue is `const isValid = await verifySolution(solution, hmacKey);` is returning false always..

Do you have an idea why?

**Comment by ovx** [comment]
@andrevferreiraa  The function `solveChallenge` returns only `{ number }`, so to verify the solution you have merge the original `challenge` with `solution`, like this based on your code:

```js
const token = await fetchAppCheckToken({
  solution: {
    ...challengeResponse.data,
    ...solution,
  },
})
```
And thanks for the tip about the permissions, using the cli helped.

**Comment by ovx** [comment]
Now there's also an official extension and client provider: https://github.com/altcha-org/firebase-app-check (the extension isn't published/verified yet).

**Comment by andrevferreiraa** [comment]
Great news about the extension! I'm trying to use it but it seems that in the createAppCheckTokenUrl function, i'm getting an empty body and a buffer in the rawBody. Did you find a way to parse that into json by any chance?

**Comment by andrevferreiraa** [comment]
After parsing the rawBody like this:
`    const rawBody = Buffer.from(req.rawBody, 'hex').toString('utf-8')`
This is the string:
`{"solution":{"solution":{"number":594213,"took":11993}}}`

The body should be `{"solution":{"number":594213,"took":11993}}` instead

**Comment by ovx** [comment]
I think you just need to set `content-type: application/json` on the request. The library @altcha/firebase-app-check does that and it works fine (with `fetch`). Also if you're using the extension with you custom client code, the payload to the createAppCheckToken function is different: 

```js
{
  appId: '...',
  payload: {
    ...challenge,
    number: solution.number,
  },
}
```

**Comment by andrevferreiraa** [comment]
Sorry, one last question. How did you return the token from function?
I tried both `res.json({ token })` and ` res.send(token)`. 

First one i get the "Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds." and second one just breaks completely because the extension expects a json.

**Comment by ovx** [comment]
The source is available here: https://github.com/altcha-org/firebase-app-check-provider/blob/main/functions/src/index.ts#L64

But timeout seems more like it could be a problem with high complexity - the default with extension is only 10,000 (maxnumber), I suppose that the whole AppCheck exchange is counted to the operation timeout, so the whole thing must fast.

**Comment by andrevferreiraa** [comment]
Yup, reducing complexity solved the issue :) Thank you @ovx !
