### ISSUE TITLE
Incorrect parameter naming in worker.js

### ISSUE THREAD

**Issue by Sozdatyel** [altcha-org/altcha-lib#13]
I encountered an issue with the `solveChallengeWorkers` function while using the `altcha-lib` library. The `algorithm` parameter passed to the worker gets lost due to a mismatch in parameter naming. Specifically, in `worker.js`, the variable `alg` is used instead of `algorithm`.

This causes the `solveChallenge` function to receive `undefined` as the algorithm, leading to the worker always returning `null`.

**Steps to Reproduce:**
1. Call `solveChallengeWorkers` with valid `challenge`, `salt`, and `algorithm` parameters.
2. Result of the `undefined` task check

**My code:**
```javascript
import axios from 'axios';
import { solveChallengeWorkers } from 'altcha-lib';
import workerUrl from 'altcha-lib/worker?worker';

const response = await axios.post('/backend/api/altcha-generate');
console.log('Challenge data:', {
    challenge: response.data.challenge,
    salt: response.data.salt,
    algorithm: response.data.algorithm,
});
const solution = await solveChallengeWorkers(
    workerUrl,
    8,
    response.data.challenge,
    response.data.salt,
    response.data.algorithm
);
console.log('Solving:', solution);
```

**Proposed Solution:** Change `alg` to `algorithm` in `worker.js`:
```javascript
const { algorithm, challenge, max, salt, start } = payload || {};
const result = solveChallenge(challenge, salt, algorithm, max, start);
```

**Environment:**
altcha-lib version: 1.1.1
Environment: NodeJS, Vite v6.0.3, Vue3 v3.5.13, Inertiajs v2.0.0

Thank you for your work on this library!

**Comment by ovx** [comment]
Hi, thank you for reporting this issues. Fixed in v1.2.0.
