### ISSUE TITLE
Some disabled rules aren't ignored

### ISSUE THREAD

**Issue by MrTimber** [altcha-org/altcha-lib#7]
Hi,

I have a form without textarea, and just some text :
- 2 'text' fields: 'nom' and 'prenom' (first name and last name)
- 1 'email' field: 'email'
- 1 'tel' field: 'tel'
- 2 'number' fields: 'cp' (zip code) and 'effectif' (number of persons)

![image](https://github.com/user-attachments/assets/4e5d44ea-0218-4b14-bfbc-61daea94f1c6)

I configured Altcha to disable the following rules: `text.CAPITALIZATION`, `text.CURRENCY`, `email.FREE_PROVIDER`, `ipAddress.HOSTING`, `text.UNKNOWN_LANGUAGE`, `text.UNEXPECTED_LANGUAGE`, `text.SHORT_TEXT`, `text.NUMBERS_ONLY`

![image](https://github.com/user-attachments/assets/8a011352-655b-43ec-839c-07f0efda37b2)

The list of rules to ignore is sent by the Altcha widget when you check the box:

![image](https://github.com/user-attachments/assets/d970f068-a020-493e-ba38-caa6704d76ae)

But here is the response of the Alcha server:
![image](https://github.com/user-attachments/assets/62a0eb95-b872-432e-912c-f2f6e053e5a3)

Rules `text.CAPITALIZATION`, `text.SHORT_TEXT`, and `email.FREE_PROVIDER` are indeed ignored, **but `text.UNKNOWN_LANGUAGE` rule isn't ignored** (and an other test shows that `text.UNEXPECTED_LANGUAGE` isn't ignored either).

Is it because the `expectedLangages` option is automatically configured according to the browser language?

**Comment by MrTimber** [comment]
Even setting the `expectedLangages` ​​option to an empty array, the problem is still the same

**Comment by ovx** [comment]
Hi, thanks for reporting. It was bug a in the Spam Filter, fixed in both regions.
