### ISSUE TITLE
1.0.0 `verifySolution` always returns false

### ISSUE THREAD

**Issue by vaaski** [altcha-org/altcha-lib#8]
Hey, shortly after implementing altcha into my site, the 1.0.0 update came out.

Unfortunately, it seems to have broken the functionality for my Nuxt page.
I confirmed that just updating `altcha-lib` yields the same broken state as updating both `altcha` and `altcha-lib` to 1.0.0.

Here is the PR and preview URL for my website in which it stopped working: https://github.com/vaaski/vaaski.dev/pull/178#issuecomment-2336883138

The live version at vaaski.dev still uses `altcha` 0.9.0 and `altcha-lib` 0.5.1

I might have used altcha wrong, so here is the relevant code:
- [creating the challenge](https://github.com/vaaski/vaaski.dev/blob/2024/functions/generate-challenge.mts)
- [verifying the challenge](https://github.com/vaaski/vaaski.dev/blob/2024/functions/send-message.mts#L23)
- client-side code (Nuxt 3)
	- [altcha component](https://github.com/vaaski/vaaski.dev/blob/2024/components/captcha-widget.client.vue)
	- [contact form](https://github.com/vaaski/vaaski.dev/blob/2024/components/contact-form.vue)
	- [contact page](https://github.com/vaaski/vaaski.dev/blob/2024/pages/contact.vue#L11-L15)

Has the API changed in 1.0.0? The [example in the readme](https://github.com/altcha-org/altcha-lib#usage) still looks the same.

**Comment by ovx** [comment]
Hi, the only difference is how `expires` is being checked - from version 1.0 the check fails if the `expires` is not set in the challenge (the previous versions pass if expires is not present in the challenge). So you have to disable `checkExpires` (by providing false as the third argument of the `verifySolution` function), or better, enable challenge expiration when generating the challenge by providing `expires` parameter to the `createChallenge` function.

I'll add some default expires to the `createChallenge` function in the next version to prevent this issue.

**Comment by vaaski** [comment]
Yes, setting `expires` has indeed fixed the issue. Thank you for the swift reply.

A default `expires` would be great, but until then, what do you suggest? An hour?

**Comment by ovx** [comment]
Yes, 1 hour should be good for most cases.

**Comment by vaaski** [comment]
Perfect, thank you!

**Comment by ovx** [comment]
The strict `expires` verification has been reverted in the version `1.1.0` to prevent similar issues. It's actually not needed as the `expires` attribute is signed and other libraries also don't include default expires.
